apiVersion: cloud.streamnative.io/v1alpha1
kind: Function
metadata:
  name: py-function-sample
  namespace: default
spec:
  className: exclamation_function.ExclamationFunction
  sourceType: java.lang.String
  sinkType: java.lang.String
  forwardSourceMessageProperty: true
  MaxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 1
  logTopic: persistent://public/default/py-function-logs
  input:
    topics:
    - persistent://public/default/py-function-input-topic
  output:
    topic: persistent://public/default/py-function-output-topic
  resources:
    requests:
      cpu: "0.1"
      memory: 1G
    limits:
      cpu: "0.2"
      memory: 1.1G
  # each secret will be loaded ad an env variable from the `path` secret with the `key` in that secret in the name of `name`
  secretsMap:
    "name":
        path: "test-py-secret"
        key: "username"
    "pwd":
        path: "test-py-secret"
        key: "password"
  pulsar:
    pulsarConfig: "test-py-pulsar"
    #authConfig: "test-auth"
  python:
    py: exclamation_function.py
    pyLocation: public/default/nlu-test-py-function
  # to be delete & use admission hook
  clusterName: test-pulsar
  autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-py-pulsar
data:
    webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
    brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: test-auth
#data:
#  clientAuthenticationPlugin: "abc"
#  clientAuthenticationParameters: "xyz"
#  tlsTrustCertsFilePath: "uvw"
#  useTls: "true"
#  tlsAllowInsecureConnection: "false"
#  tlsHostnameVerificationEnable: "true"
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: test-py-secret
type: Opaque
