apiVersion: cloud.streamnative.io/v1alpha1
kind: FunctionMesh
metadata:
  name: functionmesh-sample
spec:
  functions:
    - name: ex1
      className: org.apache.pulsar.functions.api.examples.ExclamationFunction
      sourceType: java.lang.String
      sinkType: java.lang.String
      replicas: 1
      maxReplicas: 1
      logTopic: persistent://public/default/logging-function-log
      input:
        topics:
          - persistent://public/default/functionmesh-input-topic
      output:
        topic: persistent://public/default/mid-topic
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      java:
        jar: pulsar-functions-api-examples.jar
        jarLocation: public/default/nlu-test-functionmesh-ex1
      # following value must be provided if no auto-filling is enabled
      forwardSourceMessageProperty: true
      autoAck: true
      resources:
        requests:
          cpu: "0.1"
          memory: 1G
        limits:
          cpu: "0.2"
          memory: 1.1G
      clusterName: test-pulsar
    - name: ex2
      className: org.apache.pulsar.functions.api.examples.ExclamationFunction
      sourceType: java.lang.String
      sinkType: java.lang.String
      replicas: 1
      maxReplicas: 1
      logTopic: persistent://public/default/logging-function-logs
      input:
        topics:
          - persistent://public/default/mid-topic
      output:
        topic: persistent://public/default/functionmesh-output-topic
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      java:
        jar: pulsar-functions-api-examples.jar
        jarLocation: public/default/nlu-test-functionmesh-ex2
      # following value must be provided if no auto-filling is enabled
      forwardSourceMessageProperty: true
      autoAck: true
      resources:
        requests:
          cpu: "0.1"
          memory: 1G
        limits:
          cpu: "0.2"
          memory: 1.1G
      clusterName: test-pulsar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-test-pulsar
data:
  webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
  brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650

