
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: sinks.cloud.streamnative.io
spec:
  group: cloud.streamnative.io
  names:
    kind: Sink
    listKind: SinkList
    plural: sinks
    singular: sink
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.selector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      description: Topic is the Schema for the sinks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SinkSpec defines the desired state of Topic
          properties:
            autoAck:
              type: boolean
            className:
              type: string
            cleanupSubscription:
              type: boolean
            clusterName:
              type: string
            deadLetterTopic:
              type: string
            golang:
              properties:
                go:
                  type: string
              type: object
            input:
              properties:
                customSchemaSources:
                  additionalProperties:
                    type: string
                  type: object
                customSerdeSources:
                  additionalProperties:
                    type: string
                  type: object
                sourceSpecs:
                  additionalProperties:
                    properties:
                      consumerProperties:
                        additionalProperties:
                          type: string
                        type: object
                      isRegexPattern:
                        type: boolean
                      receiverQueueSize:
                        format: int32
                        type: integer
                      schemaProperties:
                        additionalProperties:
                          type: string
                        type: object
                      schemaType:
                        type: string
                      serdeClassname:
                        type: string
                    type: object
                  type: object
                topicPattern:
                  type: string
                topics:
                  items:
                    type: string
                  type: array
              type: object
            java:
              properties:
                jar:
                  type: string
                jarLocation:
                  type: string
              type: object
            maxMessageRetry:
              format: int32
              type: integer
            maxReplicas:
              format: int32
              type: integer
            name:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            negativeAckRedeliveryDelayMs:
              format: int32
              type: integer
            processingGuarantee:
              type: string
            pulsar:
              properties:
                authConfig:
                  type: string
                pulsarConfig:
                  description: The config map need to contain the following fields
                    webServiceURL brokerServiceURL
                  type: string
              type: object
            python:
              properties:
                py:
                  type: string
              type: object
            replicas:
              format: int32
              type: integer
            resources:
              additionalProperties:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              description: ResourceList is a set of (resource name, quantity) pairs.
              type: object
            retainOrdering:
              type: boolean
            runtimeFlags:
              type: string
            secretsMap:
              additionalProperties:
                properties:
                  key:
                    type: string
                  path:
                    type: string
                type: object
              type: object
            sinkConfig:
              additionalProperties:
                type: string
              type: object
            sinkType:
              type: string
            sourceType:
              type: string
            subscriptionName:
              type: string
            subscriptionPosition:
              type: string
            tenant:
              type: string
            timeout:
              format: int32
              type: integer
          type: object
        status:
          description: SinkStatus defines the observed state of Topic
          properties:
            conditions:
              additionalProperties:
                description: The `Status` of a given `Condition` and the `Action`
                  needed to reach the `Status`
                properties:
                  action:
                    type: string
                  condition:
                    type: string
                  status:
                    type: string
                type: object
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: object
            replicas:
              format: int32
              type: integer
            selector:
              type: string
          required:
          - conditions
          - replicas
          - selector
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
