
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: functionmeshes.cloud.streamnative.io
spec:
  group: cloud.streamnative.io
  names:
    kind: FunctionMesh
    listKind: FunctionMeshList
    plural: functionmeshes
    singular: functionmesh
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: FunctionMesh is the Schema for the functionmeshes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FunctionMeshSpec defines the desired state of FunctionMesh
          properties:
            functions:
              items:
                description: FunctionSpec defines the desired state of Function
                properties:
                  autoAck:
                    type: boolean
                  className:
                    type: string
                  cleanupSubscription:
                    type: boolean
                  clusterName:
                    type: string
                  deadLetterTopic:
                    type: string
                  forwardSourceMessageProperty:
                    type: boolean
                  funcConfig:
                    additionalProperties:
                      type: string
                    type: object
                  golang:
                    properties:
                      go:
                        type: string
                    type: object
                  input:
                    properties:
                      customSchemaSources:
                        additionalProperties:
                          type: string
                        type: object
                      customSerdeSources:
                        additionalProperties:
                          type: string
                        type: object
                      sourceSpecs:
                        additionalProperties:
                          properties:
                            consumerProperties:
                              additionalProperties:
                                type: string
                              type: object
                            isRegexPattern:
                              type: boolean
                            receiverQueueSize:
                              format: int32
                              type: integer
                            schemaProperties:
                              additionalProperties:
                                type: string
                              type: object
                            schemaType:
                              type: string
                            serdeClassname:
                              type: string
                          type: object
                        type: object
                      topicPattern:
                        type: string
                      topics:
                        items:
                          type: string
                        type: array
                    type: object
                  java:
                    properties:
                      jar:
                        type: string
                      jarLocation:
                        type: string
                    type: object
                  logTopic:
                    type: string
                  maxMessageRetry:
                    format: int32
                    type: integer
                  maxPendingAsyncRequests:
                    format: int32
                    type: integer
                  maxReplicas:
                    format: int32
                    type: integer
                  name:
                    description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of
                      cluster Important: Run "make" to regenerate code after modifying
                      this file'
                    type: string
                  output:
                    properties:
                      customSchemaSinks:
                        additionalProperties:
                          type: string
                        type: object
                      producerConf:
                        properties:
                          maxPendingMessages:
                            format: int32
                            type: integer
                          maxPendingMessagesAcrossPartitions:
                            format: int32
                            type: integer
                          useThreadLocalProducers:
                            type: boolean
                        type: object
                      sinkSchemaType:
                        type: string
                      sinkSerdeClassName:
                        type: string
                      topic:
                        type: string
                    type: object
                  processingGuarantee:
                    type: string
                  pulsar:
                    properties:
                      authConfig:
                        type: string
                      pulsarConfig:
                        description: The config map need to contain the following
                          fields webServiceURL brokerServiceURL
                        type: string
                    type: object
                  python:
                    properties:
                      py:
                        type: string
                    type: object
                  replicas:
                    format: int32
                    type: integer
                  resources:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: ResourceList is a set of (resource name, quantity)
                      pairs.
                    type: object
                  retainKeyOrdering:
                    type: boolean
                  retainOrdering:
                    type: boolean
                  runtimeFlags:
                    type: string
                  secretsMap:
                    additionalProperties:
                      properties:
                        key:
                          type: string
                        path:
                          type: string
                      type: object
                    type: object
                  sinkType:
                    type: string
                  sourceType:
                    type: string
                  subscriptionName:
                    type: string
                  subscriptionPosition:
                    type: string
                  tenant:
                    type: string
                  timeout:
                    format: int32
                    type: integer
                type: object
              type: array
            sinks:
              items:
                description: SinkSpec defines the desired state of Topic
                properties:
                  autoAck:
                    type: boolean
                  className:
                    type: string
                  cleanupSubscription:
                    type: boolean
                  clusterName:
                    type: string
                  deadLetterTopic:
                    type: string
                  golang:
                    properties:
                      go:
                        type: string
                    type: object
                  input:
                    properties:
                      customSchemaSources:
                        additionalProperties:
                          type: string
                        type: object
                      customSerdeSources:
                        additionalProperties:
                          type: string
                        type: object
                      sourceSpecs:
                        additionalProperties:
                          properties:
                            consumerProperties:
                              additionalProperties:
                                type: string
                              type: object
                            isRegexPattern:
                              type: boolean
                            receiverQueueSize:
                              format: int32
                              type: integer
                            schemaProperties:
                              additionalProperties:
                                type: string
                              type: object
                            schemaType:
                              type: string
                            serdeClassname:
                              type: string
                          type: object
                        type: object
                      topicPattern:
                        type: string
                      topics:
                        items:
                          type: string
                        type: array
                    type: object
                  java:
                    properties:
                      jar:
                        type: string
                      jarLocation:
                        type: string
                    type: object
                  maxMessageRetry:
                    format: int32
                    type: integer
                  maxReplicas:
                    format: int32
                    type: integer
                  name:
                    description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of
                      cluster Important: Run "make" to regenerate code after modifying
                      this file'
                    type: string
                  negativeAckRedeliveryDelayMs:
                    format: int32
                    type: integer
                  processingGuarantee:
                    type: string
                  pulsar:
                    properties:
                      authConfig:
                        type: string
                      pulsarConfig:
                        description: The config map need to contain the following
                          fields webServiceURL brokerServiceURL
                        type: string
                    type: object
                  python:
                    properties:
                      py:
                        type: string
                    type: object
                  replicas:
                    format: int32
                    type: integer
                  resources:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: ResourceList is a set of (resource name, quantity)
                      pairs.
                    type: object
                  retainOrdering:
                    type: boolean
                  runtimeFlags:
                    type: string
                  secretsMap:
                    additionalProperties:
                      properties:
                        key:
                          type: string
                        path:
                          type: string
                      type: object
                    type: object
                  sinkConfig:
                    additionalProperties:
                      type: string
                    type: object
                  sinkType:
                    type: string
                  sourceType:
                    type: string
                  subscriptionName:
                    type: string
                  subscriptionPosition:
                    type: string
                  tenant:
                    type: string
                  timeout:
                    format: int32
                    type: integer
                type: object
              type: array
            sources:
              items:
                description: SourceSpec defines the desired state of Source
                properties:
                  className:
                    type: string
                  clusterName:
                    type: string
                  golang:
                    properties:
                      go:
                        type: string
                    type: object
                  java:
                    properties:
                      jar:
                        type: string
                      jarLocation:
                        type: string
                    type: object
                  maxReplicas:
                    format: int32
                    type: integer
                  name:
                    description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of
                      cluster Important: Run "make" to regenerate code after modifying
                      this file'
                    type: string
                  output:
                    properties:
                      customSchemaSinks:
                        additionalProperties:
                          type: string
                        type: object
                      producerConf:
                        properties:
                          maxPendingMessages:
                            format: int32
                            type: integer
                          maxPendingMessagesAcrossPartitions:
                            format: int32
                            type: integer
                          useThreadLocalProducers:
                            type: boolean
                        type: object
                      sinkSchemaType:
                        type: string
                      sinkSerdeClassName:
                        type: string
                      topic:
                        type: string
                    type: object
                  processingGuarantee:
                    type: string
                  pulsar:
                    properties:
                      authConfig:
                        type: string
                      pulsarConfig:
                        description: The config map need to contain the following
                          fields webServiceURL brokerServiceURL
                        type: string
                    type: object
                  python:
                    properties:
                      py:
                        type: string
                    type: object
                  replicas:
                    format: int32
                    type: integer
                  resources:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: ResourceList is a set of (resource name, quantity)
                      pairs.
                    type: object
                  runtimeFlags:
                    type: string
                  secretsMap:
                    additionalProperties:
                      properties:
                        key:
                          type: string
                        path:
                          type: string
                      type: object
                    type: object
                  sinkType:
                    type: string
                  sourceConfig:
                    additionalProperties:
                      type: string
                    type: object
                  sourceType:
                    type: string
                  tenant:
                    type: string
                type: object
              type: array
          type: object
        status:
          description: FunctionMeshStatus defines the observed state of FunctionMesh
          properties:
            functionConditions:
              additionalProperties:
                description: The `Status` of a given `Condition` and the `Action`
                  needed to reach the `Status`
                properties:
                  action:
                    type: string
                  condition:
                    type: string
                  status:
                    type: string
                type: object
              type: object
            sinkConditions:
              additionalProperties:
                description: The `Status` of a given `Condition` and the `Action`
                  needed to reach the `Status`
                properties:
                  action:
                    type: string
                  condition:
                    type: string
                  status:
                    type: string
                type: object
              type: object
            sourceConditions:
              additionalProperties:
                description: The `Status` of a given `Condition` and the `Action`
                  needed to reach the `Status`
                properties:
                  action:
                    type: string
                  condition:
                    type: string
                  status:
                    type: string
                type: object
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
