---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: connectorcatalogs.compute.functionmesh.io
spec:
  group: compute.functionmesh.io
  names:
    kind: ConnectorCatalog
    listKind: ConnectorCatalogList
    plural: connectorcatalogs
    singular: connectorcatalog
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              connectorDefinitions:
                items:
                  properties:
                    configFieldDefinitions:
                      items:
                        properties:
                          attributes:
                            additionalProperties:
                              type: string
                            type: object
                          fieldName:
                            type: string
                          typeName:
                            type: string
                        required:
                        - fieldName
                        - typeName
                        type: object
                      type: array
                    defaultSchemaType:
                      type: string
                    defaultSerdeClassName:
                      type: string
                    description:
                      type: string
                    id:
                      type: string
                    imageRegistry:
                      type: string
                    imageRepository:
                      type: string
                    imageTag:
                      type: string
                    jarFullName:
                      type: string
                    name:
                      type: string
                    sinkClass:
                      type: string
                    sinkConfigClass:
                      type: string
                    sinkTypeClassName:
                      type: string
                    sourceClass:
                      type: string
                    sourceConfigClass:
                      type: string
                    sourceTypeClassName:
                      type: string
                    typeClassName:
                      type: string
                    version:
                      type: string
                  required:
                  - id
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - id
                x-kubernetes-list-type: map
            required:
            - connectorDefinitions
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
