name: Function-Mesh Release

on:
  release:
    types: [created]

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up GO 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: setup kubebuilder 2.3.1
        uses: RyanSiu1995/kubebuilder-action@v1.1
        with:
          version: 2.3.1

      - name: build release
        id: build_release
        env:
          VERSION: ${{ github.event.release.tag_name }}
          IMAGE_TAG_BASE: streamnative/function-mesh
          CATALOG_BRANCH_IMG: latest
        run: |
          make release
          make docker-push
          make docker-build image-push catalog-build catalog-push

      - name: Upload crd.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: manifests/crd.yaml
          asset_name: crd.yaml
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload rbac.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: manifests/rbac.yaml
          asset_name: rbac.yaml
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload install.sh to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: install.sh
          asset_name: install.sh
          tag: ${{ github.ref }}
          overwrite: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --help

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: tuteng
          password: ${{ secrets.IMAGE_GITHUB_TOKEN }}

      - name: Auto generate crd model
        run: cd java-proxy && ./tool/generate-crd.sh

      - name: Format license
        run: cd java-proxy && mvn license:format

      - name: Run mesh proxy unit test
        run: |
          cd java-proxy
          mvn clean install

      - name: Upload java proxy nar package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: java-proxy/target/java-proxy-${{ github.event.release.tag_name }}.nar
          asset_name: java-proxy-${{ github.event.release.tag_name }}.nar
          tag: ${{ github.ref }}
          overwrite: true
