name: Precommit - Test Function Kind with Key Based Batcher
on:
  pull_request:
    branches:
      - '*'
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy k8s cluster env
        run: |
          .ci/deploy_pulsar_cluster.sh

      - name: Build runner images
        run: |
          PULSAR_IMAGE_TAG=2.7.1 PULSAR_IMAGE=apachepulsar/pulsar-all KIND_PUSH=true images/build.sh

      - name: Install operator-sdk
        run: |
          RELEASE_VERSION=v1.2.0
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

      #      - name: Add CRD, controller or webhooks
      #        run: |
      #          operator-sdk create api --group cloud --version v1alpha1 --kind Function --resource=true --controller=true
      #          operator-sdk create webhook --group compute.functionmesh.io --version v1alpha1 --kind Function --defaulting --programmatic-validation

      - name: Deploy function mesh server
        run: |
          make generate
          make install
          nohup make run &

      - name: Test Function kind
        run: |
          kubectl apply -f config/samples/compute_v1alpha1_function_key_based_batcher.yaml
          kubectl get all

      - name: Verify Function Mesh
        run: |
          .ci/verify_function_mesh.sh java-function-batcher-sample
