name: Precommit - Integration Tests
on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'PROJECT'
      - 'LICENSE'
      - 'mesh-worker-service/README.md'
      - 'tools/README.md'
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy k8s cluster env
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: |
            .ci/deploy_pulsar_cluster.sh
          on_retry_command: |
            .ci/cleanup.sh

      - name: Install cert manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager --set installCRDs=true

      - name: Build runner images
        run: |
          PULSAR_IMAGE_TAG=2.9.2.23 PULSAR_IMAGE=streamnative/pulsar-all KIND_PUSH=true images/build.sh
          PULSAR_IMAGE_TAG=2.9.2.23 KIND_PUSH=true images/samples/build.sh

      - name: Install operator-sdk
        run: |
          RELEASE_VERSION=v1.6.1
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

      - name: setup kubebuilder 2.3.1
        uses: RyanSiu1995/kubebuilder-action@v1.2.1
        with:
          version: 2.3.1

      #      - name: Add CRD, controller or webhooks
      #        run: |
      #          operator-sdk create api --group compute --version v1alpha1 --kind Function --resource=true --controller=true
      #          operator-sdk create webhook --group compute.functionmesh.io --version v1alpha1 --kind Function --defaulting --programmatic-validation

      - name: Build and load function-mesh operator image
        run: |
          make generate
          make helm-crds
          image="function-mesh-operator:latest"
          IMG=${image} make docker-build-skip-test
          clusters=$(kind get clusters)
          for cluster in $clusters; do
            kind load docker-image --name ${cluster} ${image}
          done

      - name: Deploy function mesh server
        run: |
          helm install function-mesh -n function-mesh --set operatorImage=function-mesh-operator:latest --create-namespace charts/function-mesh-operator
          kubectl wait --for=condition=Ready -l app.kubernetes.io/name=function-mesh-operator pods -n function-mesh --timeout=5m
          num=0
          while [[ ${num} -lt 1 ]]; do
            sleep 5s
            kubectl get pods -n function-mesh
            num=$(kubectl logs -n function-mesh -l app.kubernetes.io/name=function-mesh-operator --tail=-1 | grep "serving webhook server" | wc -l)
          done

      - name: Test Function kind - Java Function
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_function.yaml
          kubectl get all

      - name: Verify Function kind - Java Function
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_function.yaml

      - name: Test Function kind - Python Function
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_py_function.yaml
          kubectl get all

      - name: Verify Function kind - Python Function
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_py_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_py_function.yaml

      - name: Test Function kind - Go Function
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_go_function.yaml
          kubectl get all

      - name: Verify Function kind - Go Function
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_go_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_go_function.yaml

      - name: Test Function kind - Java Function with download from pulsar
        run: |
          .ci/upload_function.sh java
          kubectl apply -f .ci/clusters/compute_v1alpha1_download_function.yaml
          kubectl get all

      - name: Verify Function kind - Java Function with download from pulsar
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_download_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_download_function.yaml

      - name: Test Function kind - Go Function with download from pulsar
        run: |
          .ci/upload_function.sh go
          kubectl apply -f .ci/clusters/compute_v1alpha1_download_go_function.yaml
          kubectl get all

      - name: Verify Function kind - Go Function with download from pulsar
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_download_go_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_download_go_function.yaml

      - name: Test Function kind - Python Function with download from pulsar
        run: |
          .ci/upload_function.sh py
          kubectl apply -f .ci/clusters/compute_v1alpha1_download_py_function.yaml
          kubectl get all

      - name: Verify Function kind - Python Function with download from pulsar
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_download_py_function
          kubectl delete -f .ci/clusters/compute_v1alpha1_download_py_function.yaml

      - name: Test Mesh kind
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_functionmesh.yaml
          kubectl get all

      - name: Verify Mesh kind
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_functionmesh
          kubectl delete -f .ci/clusters/compute_v1alpha1_functionmesh.yaml

      - name: Test Function HPA
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_function_hpa.yaml
          kubectl get all

      - name: Verify Function HPA
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_function_hpa
          kubectl delete -f .ci/clusters/compute_v1alpha1_function_hpa.yaml

      - name: Test Function Builtin HPA
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_function_builtin_hpa.yaml
          kubectl get all

      - name: Verify Function Builtin HPA
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_function_builtin_hpa
          kubectl delete -f .ci/clusters/compute_v1alpha1_function_builtin_hpa.yaml

      - name: Test Python Stateful Function
        run: |
          kubectl apply -f .ci/clusters/compute_v1alpha1_function_stateful.yaml
          kubectl get all

      - name: Verify Python Stateful Function
        run: |
          .ci/verify_function_mesh.sh compute_v1alpha1_function_stateful
          kubectl delete -f .ci/clusters/compute_v1alpha1_function_stateful.yaml

#       - name: Test Sink Kind - Install ES Server
#         run: |
#           kubectl apply -f https://download.elastic.co/downloads/eck/1.2.1/all-in-one.yaml
#           kubectl apply -f config/samples/elasticsearch.yaml
#
#       - name: Test Sink Kind - Start Sink Kind
#         run: |
#           kubectl apply -f config/samples/compute_v1alpha1_sink.yaml
#           kubectl get sinks
#
#       - name: Verify Sink
#         run: |
#           .ci/verify_function_mesh.sh sink-sample
#           kubectl delete -f config/samples/compute_v1alpha1_sink.yaml
#           kubectl delete -f config/samples/elasticsearch.yaml
#           kubectl delete -f https://download.elastic.co/downloads/eck/1.2.1/all-in-one.yaml
#
#       - name: Test Source Kind - Install Mongo DB Server
#         run: |
#           kubectl apply -f config/samples/mongodb-dbz.yaml
#
#       - name: Test Source Kind - Start Source Kind
#         run: |
#           kubectl apply -f config/samples/compute_v1alpha1_source.yaml
#           kubectl get sources
#
#       - name: Verify Source
#         run: |
#           .ci/verify_function_mesh.sh source-sample
#           kubectl delete -f config/samples/compute_v1alpha1_source.yaml
#           kubectl delete -f config/samples/mongodb-dbz.yaml
#
#       - name: Test Function kind
#         run: |
#           kubectl apply -f config/samples/compute_v1alpha1_function_key_based_batcher.yaml
#           kubectl get all
#
#       - name: Verify Function Mesh
#         run: |
#           .ci/verify_function_mesh.sh java-function-batcher-sample
#
#       - name: Test Crypto Function kind
#         run: |
#           kubectl apply -f config/samples/compute_v1alpha1_function_crypto.yaml
#           kubectl get all
#
#       - name: Verify Crypto Function Mesh
#         run: |
#           .ci/verify_function_mesh.sh function-crypto-sample
#           kubectl delete -f config/samples/compute_v1alpha1_function_crypto.yaml

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()
